language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.6.6
      script:
        - bundle exec danger
    - rvm: 2.6.6
      env: DATABASE_ADAPTER=activerecord
      services:
        - postgresql
    - rvm: 2.6.6
      env: DATABASE_ADAPTER=mongoid
      services:
        - mongodb

script:
  - bundle exec rake
  - BUNDLE_GEMFILE=Gemfile && cd sample_apps/sample_app_$DATABASE_ADAPTER && bundle && RACK_ENV=test bundle exec rake
